# Site settings
title: Carpe Diem
author: Sreedevi Vedula
#header-img: img/home-bg.jpg
default-img: img/default-img.JPG
email: suryasreevedula@gmail.com
description: "Technology Blog"
baseurl: ""
url: "http://sreedevivedula.github.io"
twitter_username: suryasreevedula
github_username:  sreedevivedula

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
