# Site settings
title: Clean Blog
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: "Technology. Testing. Thoughts."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: SBootstrap
github_username:  sreedevivedula
facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
